name: "Welcome Message"
on: [push]
jobs:
  Job-Message-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Welcome to NubeEra"
      - run: echo "Current OS is ${{runner.os}} "
      - run: echo "Github Event Name is ${{github.event_name}} "
      - run: pwd
      - run: ls ~
      - run: ls ${{github.workspace}}